### ISSUE TITLE
Query syntax

### ISSUE THREAD

**Issue by norbert-tasi** [cancerberoSgx/node-lucene#1]
Hello,

This is a great library.
I just like to ask how can I query for multiple fields just like this
(title:"foo bar" AND body:"quick fox") OR title:fox
Can I create a simple text-based parser without field?

Thanks

**Comment by cancerberoSgx** [comment]
Let me investigate and come back to you. Currently, cases where you need to create a new subclass at runtime are blocked by a node-java limitation I'm currently trying to tackle or workaround: https://github.com/joeferner/node-java/issues/447

But again, let me investigate this particular case. Currently I only ported a very small part of lucene API to js. Thir project is WIP and help is most appreciated ;)

**Comment by norbert-tasi** [comment]
Thank you! 
It works just like in lucene:
http://localhost:1337/api/patient/find?filter=txt:szin AND diagns:s6000
with syntax like this where txt and diagns are my fields, the colon is the field and value separator.

Thanks
