### ISSUE TITLE
DeleteDocument

### ISSUE THREAD

**Issue by cgishack** [cancerberoSgx/node-lucene#3]
Is the IndexWriter missing a delete document function ?
https://github.com/cancerberoSgx/node-lucene/blob/master/node-lucene/src/index/IndexWriter.ts

The Java docs shows it exist.
https://lucene.apache.org/core/7_4_0/core/org/apache/lucene/index/IndexWriter.html

**Comment by cancerberoSgx** [comment]
There, I added deleteDocuments and deleteAll to IndexWriter. Take into account that many methods are missing in lucene's API . Were those you needed ?

Please report missing stuff you need here, or better if you can, just add them copying existing ones and contribute back here ;) Thanks  BTW - I updated to lucene 7.7.2 so probably you will need to change src/util/getLuceneJava.ts or rename/update  your .jars . Tell me if you have any idea to provide a friendlier API for locating lucene .jars. 

Thanks

**Comment by cgishack** [comment]
Thank you for the update!
If I see other missing functions I will try and contribute.

Drew
